### ISSUE TITLE
jcardsim 3.0.5.11 -> 3.0.6 update breaks RSA handling

### ISSUE THREAD

**Issue by mrautio** [mrautio/emv-card-simulator#18]
TODO: Check if it's issue in jcardsim or the card simulator implementation...

- https://github.com/ph4r05/jcardsim/blob/master/src/main/java/com/licel/jcardsim/crypto/AsymmetricCipherImpl.java#L103
- https://github.com/ph4r05/jcardsim/compare/3.0.5.11...3.0.6.0#diff-227265437267280e8fd3877ad34a7466770221c4b883a000663b028da50cb3e4
- https://github.com/bcgit/bc-java/blob/main/core/src/main/java/org/bouncycastle/crypto/engines/RSACoreEngine.java#L57

```
    javacard.security.CryptoException
        at javacard.security.CryptoException.throwIt(Unknown Source)
        at com.licel.jcardsim.crypto.AsymmetricCipherImpl.doFinal(AsymmetricCipherImpl.java:103)
        at emvcardsimulator.PaymentApplication.processDynamicDataAuthentication(PaymentApplication.java:241)
        at emvcardsimulator.PaymentApplication.process(PaymentApplication.java:377)
        at emvcardsimulator.PaymentApplicationContainer.process(PaymentApplicationContainer.java:24)
        at com.licel.jcardsim.base.SimulatorRuntime.transmitCommand(SimulatorRuntime.java:314)
        at com.licel.jcardsim.base.Simulator.transmitCommand(Simulator.java:260)
        at com.licel.jcardsim.smartcardio.CardSimulator.transmitCommand(CardSimulator.java:68)
        at emvcardsimulator.SmartCard.transmitCommand(SmartCard.java:69)
        at emvcardsimulator.SmartCard.transmitCommand(SmartCard.java:57)
        at emvcardsimulator.SimulatorTest.sendApduRequest(SimulatorTest.java:68)
        at emvcardsimulator.SimulatorTest.entryPoint(Native Method)
        at emvcardsimulator.SimulatorTest.simulatorEndToEndTransactionTest(SimulatorTest.java:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
        ...
```

**Comment by mrautio** [comment]
https://github.com/ph4r05/jcardsim/pull/3
